### ISSUE TITLE
Main Page on App Launch

### ISSUE THREAD

**Issue by seniorm0ment** [jtmcn/archwiki-viewer#75] opened 2020-01-26 07:08 UTC
Suggesting upon app launch, instead of a blank page, it goes to the Arch Wiki main page.
https://wiki.archlinux.org/index.php/Main_page

**Comment by kevinhinterlong** [comment] 2020-01-29 04:48
What version are you running? Are you still seeing this?

It goes to the main page for me as expected

**Comment by seniorm0ment** [comment] 2020-01-29 04:58
Weird, I'm on 1.0.14 Fdroid, but it seems like it's going to the main page rn?
Other day I tried opening and closing app a few times and it was just a blank white screen.

**Comment by kevinhinterlong** [comment] 2020-01-29 05:05
I've had that happen before and figured it was just my internet connection since I was never able to reproduce it. I'm gonna close this for now though, but thanks for the report

**Closed as completed by kevinhinterlong** 2020-01-29 05:05 UTC
